Fix: Fix the tablet breakpoint error
TheGymRwanda/unit8-maroon pull request #33
Opened 2022-12-12 07:17 UTC by haroldmud

###  PR DESCRIPTION

- This PR Fix bugs in the Expertise section

### TASKS COMPLETED

- [x] Fixing the CSS bug on the Tablet and iPad breakpoint
- [ ] Fixing the image display functionality

### HOW CAN THIS PR BE TESTED

```
git clone https://github.com/TheGymRwanda/unit8-maroon
git checkout fix/project
npm install
npm run dev

```

### BEFORE SUBMITTING YOUR PR, ENSURE IT HAS THE FOLLOWING

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard to understand areas
- [x] My changes generate no new warnings

### TICKET NUMBER

#033: https://www.notion.so/apeunit/Team-Maroon-be46fba60816476ca536e5bb54663acc?p=bc1ceaa2e69b4ca4ae3310c2cdab57f9&pm=s

2022-12-20 07:15 UTC, arjorb approved these changes
It looks good to me!

2022-12-20 07:56 UTC, ishoborabyose requested changes

2022-12-20 07:56 UTC, ishoborabyose commented on components/section/Project.jsx
> +      image:
You did a great job, the only simple thing to change is to remove white space.  try to prettier to make it perfect.

2022-12-20 07:56 UTC, ishoborabyose commented on components/section/Project.jsx
> +    },
Here too, white space is big. try to remove white spaces.

2022-12-20 07:56 UTC, ishoborabyose commented on components/section/Project.jsx
> +        "https://raw.githubusercontent.com/TheGymRwanda/unit8-red/dev/public/assets/images/bitlipa.webp",
Here as well

2022-12-20 08:22 UTC, Nkaka23dev commented on components/section/Project.jsx
>    const images = [
You did a great Job, But for best practice, it is better if you put this data in a separate files to avoid a lot of lines of code in one file.

2022-12-20 08:29 UTC, Nkaka23dev reviewed
You did a great Job, But note the following points:
1) when scrolling, the image should be fixed a bit  while the other content are moving.
2) On mobile, when I click on the last item the expected Image comes when I click on the second time.

2022-12-20 08:29 UTC, Nkaka23dev commented on components/section/Project.jsx
> -              </div>
Here,  I think you use loop instead of using individual components.

2022-12-22 09:11 UTC, Nkaka23dev approved these changes

2022-12-22 09:14 UTC, ishoborabyose approved these changes
## LGTM

2022-12-22 09:25 UTC, merged