Ft/about us mobile
TheGymRwanda/unit8-maroon pull request #7
Opened 2022-11-23 15:46 UTC by Delyc

2022-11-29 11:02 UTC, haroldmud requested changes
This is a nice job so far, there are still some tiny things you need to work on but be sure the required changes are not terrible.

- Kindly add some padding-top to the description.
<div style="flex">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/91553966/204510776-d3a673a3-5c26-413a-b922-568704c03c9a.png">
<=yours vs figma=>
<img width="269" alt="image" src="https://user-images.githubusercontent.com/91553966/204511282-4dd1a776-4cc3-4b10-98ee-6b9d7c4aa386.png">
</div>

- On the "What we do" and "Employment" button only the icons trigger the description, kindly work on that.

2022-12-01 09:52 UTC, haroldmud requested changes
@Delyc The "What we do" and "Improvement" buttons are  not clickable still but their arrow-icons...please fix that as soon as possible.

2022-12-01 11:08 UTC, haroldmud approved these changes
LGTM ✅

2022-12-01 11:21 UTC, Nkaka23dev approved these changes

2022-12-01 17:21 UTC, ishoborabyose approved these changes

2022-12-01 20:01 UTC, merged